versions:
  "1.0.0":
    folder: "pre-v5"
  "2.0.0":
    folder: "pre-v5"
  "2.1.0":
    folder: "pre-v5"
  "2.1.1":
    folder: "pre-v5"
  "2.1.2":
    folder: "pre-v5"
  "2.2.0":
    folder: "pre-v5"
  "3.0.0":
    folder: "pre-v5"
  "4.0.0":
    folder: "pre-v5"
  "4.1.0":
    folder: "pre-v5"
  "4.1.1":
    folder: "pre-v5"
  "5.0.0":
    folder: "v5"
  "5.0.1":
    folder: "v5"
  "9.9.9":
    folder: "v5"
